### ISSUE TITLE
在GTL1.3.1服务端上的异常

### ISSUE THREAD

**Issue by xfpuls** [liansishen/GTMThings#7]
-- Head --
Thread: main
Suspected Mod: 
        GTMThings (gtmthings), Version: 1.2.3-build_30
                at TRANSFORMER/gtmthings@1.2.3-build_30/com.hepdd.gtmthings.data.CustomItems.registerTieredCover(CustomItems.java:108)
Stacktrace:
        at com.hepdd.gtmthings.data.CustomItems.registerTieredCover(CustomItems.java:108) ~[gtmthings-1.2.3-build_30.jar%23301!/:1.2.3-build_30] {re:classloading}
-- MOD gtmthings --
Details:
        Caused by 0: java.lang.ExceptionInInitializerError
                at com.hepdd.gtmthings.GTMThings.registerCovers(GTMThings.java:88) ~[gtmthings-1.2.3-build_30.jar%23301!/:1.2.3-build_30] {re:classloading}
                at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:263) ~[eventbus-6.0.5.jar%23150!/:?] {}
                at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:255) ~[eventbus-6.0.5.jar%23150!/:?] {}
                at net.minecraftforge.eventbus.EventBus.post(EventBus.java:319) ~[eventbus-6.0.5.jar%23150!/:?] {}
                at net.minecraftforge.eventbus.EventBus.post(EventBus.java:299) ~[eventbus-6.0.5.jar%23150!/:?] {}
                at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:155) ~[javafmllanguage-1.20.1-47.3.5.jar%23328!/:?] {}
                at net.minecraftforge.fml.ModLoader.lambda$postEvent$29(ModLoader.java:326) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
                at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
                at net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:227) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
                at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:326) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
                at com.gregtechceu.gtceu.common.data.GTCovers.init(GTCovers.java:169) ~[gtceu-1.20.1-1.3.1.jar%23300!/:?] {re:classloading}
                at com.gregtechceu.gtceu.common.CommonProxy.init(CommonProxy.java:125) ~[gtceu-1.20.1-1.3.1.jar%23300!/:?] {re:classloading}
                at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
                at net.minecraftforge.fml.DeferredWorkQueue.lambda$makeRunnable$2(DeferredWorkQueue.java:81) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
                at net.minecraftforge.fml.DeferredWorkQueue.makeRunnable(DeferredWorkQueue.java:76) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
                at net.minecraftforge.fml.DeferredWorkQueue.lambda$runTasks$0(DeferredWorkQueue.java:60) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
                at java.util.concurrent.ConcurrentLinkedDeque.forEach(ConcurrentLinkedDeque.java:1650) ~[?:?] {re:mixin}
                at net.minecraftforge.fml.DeferredWorkQueue.runTasks(DeferredWorkQueue.java:60) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
                at net.minecraftforge.fml.core.ParallelTransition.lambda$finalActivityGenerator$2(ParallelTransition.java:35) ~[forge-1.20.1-47.3.5-universal.jar%23331!/:?] {re:classloading}
                at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?] {}
                at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
                at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:46) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
                at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:29) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
                at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:224) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
                at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:210) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
                at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
                at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:210) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
                at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:183) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
                at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
                at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
                at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:30) ~[forge-1.20.1-47.3.5-universal.jar%23331!/:?] {re:classloading}
                at net.minecraft.server.Main.main(Main.java:165) ~[server-1.20.1-20230612.114412-srg.jar%23326!/:?] {re:classloading}
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
                at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
                at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.5.jar%23192!/:?] {}
                at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.3.5.jar%23192!/:?] {}
                at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.3.5.jar%23192!/:?] {}
                at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.9.jar%23103!/:?] {}
                at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.9.jar%23103!/:?] {}
                at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.9.jar%23103!/:?] {}
                at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) [modlauncher-10.0.9.jar%23103!/:?] {}
                at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) [modlauncher-10.0.9.jar%23103!/:?] {}
                at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.9.jar%23103!/:?] {}
                at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.9.jar%23103!/:?] {}
                at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
                at com.mohistmc.MohistMCStart.main(MohistMCStart.java:109) [mohist-1.20.1-741-server.jar:1.20.1-775] {}
        Mod File: /home/container/mods/gtmthings-1.2.3-build_30.jar
        Failure message: GTMThings (gtmthings) encountered an error during the common_setup event phase
                java.lang.ExceptionInInitializerError: null
        Mod Version: 1.2.3-build_30
        Mod Issue URL: NOT PROVIDED
        Exception message: java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 8
Stacktrace:
        at com.hepdd.gtmthings.data.CustomItems.registerTieredCover(CustomItems.java:108) ~[gtmthings-1.2.3-build_30.jar%23301!/:1.2.3-build_30] {re:classloading}
        at com.hepdd.gtmthings.data.CustomItems.<clinit>(CustomItems.java:62) ~[gtmthings-1.2.3-build_30.jar%23301!/:1.2.3-build_30] {re:classloading}
        at com.hepdd.gtmthings.GTMThings.registerCovers(GTMThings.java:88) ~[gtmthings-1.2.3-build_30.jar%23301!/:1.2.3-build_30] {re:classloading}
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:263) ~[eventbus-6.0.5.jar%23150!/:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:255) ~[eventbus-6.0.5.jar%23150!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:319) ~[eventbus-6.0.5.jar%23150!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:299) ~[eventbus-6.0.5.jar%23150!/:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:155) ~[javafmllanguage-1.20.1-47.3.5.jar%23328!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$postEvent$29(ModLoader.java:326) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:227) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
        at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:326) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
        at com.gregtechceu.gtceu.common.data.GTCovers.init(GTCovers.java:169) ~[gtceu-1.20.1-1.3.1.jar%23300!/:?] {re:classloading}
        at com.gregtechceu.gtceu.common.CommonProxy.init(CommonProxy.java:125) ~[gtceu-1.20.1-1.3.1.jar%23300!/:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
        at net.minecraftforge.fml.DeferredWorkQueue.lambda$makeRunnable$2(DeferredWorkQueue.java:81) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
        at net.minecraftforge.fml.DeferredWorkQueue.makeRunnable(DeferredWorkQueue.java:76) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
        at net.minecraftforge.fml.DeferredWorkQueue.lambda$runTasks$0(DeferredWorkQueue.java:60) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
        at java.util.concurrent.ConcurrentLinkedDeque.forEach(ConcurrentLinkedDeque.java:1650) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.DeferredWorkQueue.runTasks(DeferredWorkQueue.java:60) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
        at net.minecraftforge.fml.core.ParallelTransition.lambda$finalActivityGenerator$2(ParallelTransition.java:35) ~[forge-1.20.1-47.3.5-universal.jar%23331!/:?] {re:classloading}
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
        at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:46) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
        at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:29) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:224) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:210) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:210) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:183) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[fmlcore-1.20.1-47.3.5.jar%23327!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:30) ~[forge-1.20.1-47.3.5-universal.jar%23331!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:165) ~[server-1.20.1-20230612.114412-srg.jar%23326!/:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.5.jar%23192!/:?] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.3.5.jar%23192!/:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.3.5.jar%23192!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.9.jar%23103!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.9.jar%23103!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.9.jar%23103!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) [modlauncher-10.0.9.jar%23103!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) [modlauncher-10.0.9.jar%23103!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.9.jar%23103!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.9.jar%23103!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
        at com.mohistmc.MohistMCStart.main(MohistMCStart.java:109) [mohist-1.20.1-741-server.jar:1.20.1-775] {re:classloading,re:classloading}

**Comment by liansishen** [comment]
我用了最新的构建30+网盘上的GregTech Leisure-1.3.1.0-b版本，没有出现该错误

**Comment by YiRanMushroom** [comment]
打开highTierContent应该可以解决，像是没有注册正确。

**Comment by liansishen** [comment]
#18
